### ISSUE TITLE
ERR_CONNECTION_REFUSED when loading Patreon web page

### ISSUE THREAD

**Issue by Senyu** [Alex313031/thorium-win7#7] opened 2023-07-18 02:57 UTC
**System Details**
 - OS: Windows 7 Ultimate 64-bit (x64)
 - Thorium Version 107.0.5271.0 to 109.0.5414.152 (Official Build) (64-bit)

**Problem**
After navigating to:
https://www.patreon.com
As soon as Patreon web page loads, Thorium tab goes blank and displays error message:
### This site can’t be reached
patreon.com refused to connect.
ERR_CONNECTION_REFUSED

**Screenshots**
![ere](https://github.com/Alex313031/thorium-win7/assets/75548744/aab9ac3c-3b1d-4be5-b89e-f2b2b57475e4)

**Additional Notes**
Tested on AVX, SSE3 and SSE2.

In Thorium Version 106.0.5237.0 and before the problem does not happen.

**Screenshots**
![h4](https://github.com/Alex313031/thorium-win7/assets/75548744/9a6e9465-bfa8-4a76-9e20-6bb87460feb4)

**Tested on other browsers**
**Chromium** had no problems in version 109 or before.
**Brave** had no problems in version 1.47.186 (Chromium v109).
**Edge** had no problems in version 107.
**Opera** had problem in all tested versions.
**Ungoogled Chromium** version 107 to 109 has the same problem.
**Vivaldi** had no problems in version 5.6.2867.62 (Chromium v108)
**Supermium** version 117.0.5874.0 same problem.

I tested Thorium on windows 10 22H2 Pro 64-bit (x64) with VirtualBox to see if the problem occurred in versions 110 to 114, in this case the problem happens sometimes, but when loading the page it loads normally until restart the browser.

**Comment by gz83** [comment] 2023-07-26 14:17
The issue you are experiencing cannot be reproduced in local testing. Please try to troubleshoot the problem with your current network equipment and computer. Also consider whether the network operator has taken measures to interfere with your network.

@Senyu

**Comment by Alex313031** [comment] 2023-07-26 16:17
@gz83 You can't properly test, since you are not using windows 7. I will see if I can reproduce.

Also, why do you want to use 106 if 109 fixes the issue, and is newer and backports newer thorium features?

**Comment by gz83** [comment] 2023-07-27 01:24
@Alex313031 

I am giving my opinion in view of his use environment, of course I know that the test environment is not completely correct

**Comment by Senyu** [comment] 2023-07-28 17:40
@gz83 with all due respect, but it seems you didn't read my first and second post completely where I talk about the same problem happening in other chromium based browsers.

@Alex313031 and gz83 sorry for my mistake I don't want to use 106, I'm talking about an error that happens between these versions (106 to 109) for me on some chromium based browsers (I repeat, what I did were tests) this includes:

Thorium 107 to 109.
Edge 107 to 109.
Opera all versions.
Ungoogled Chromium 107 to 109.
Supermium 115 to 117  (works on Win7)

Since the error does not happen in:
Chromium 107 to 109
Brave 1.47.186 (Chromium v109)
Vivaldi 5.6.2867.62 (Chromium v108)

I even said that in windows 10 22H2 Pro 64-bit (x64) with VirtualBox the problem happened in versions 110 to 114 sometimes, why I was doing tests (I also tested it on another computer and the same problem).
That I tested in VPN and it worked, that in the end after change IPv4 and IPv6 to google or cloudflare dns in the "internet protocol version" seems to solve the problem of Thorium or other browsers for me, so the problem is linked to DNS only in Thorium, Edge, Opera, Ungoogled Chromium, Supermium and that does not happen in Chromium, Brave and Vivaldi.

Anyway as I said in my previous post (just copied from there)
But it's still strange that it only happens from version 107 onwards in some chromium based browsers.
### **If this is happening only to me and other people did not have the "err_connection_refused", you can close this problem.**

**Comment by Alex313031** [comment] 2023-09-30 08:30
@Senyu @gz83 I really have no idea what this would be, and if it also happens in other Chromium based browsers, It probably wont be fixed. However, soon I am going to base thorium-win7 on Supermium 118, so then we won't have to worry about this.

**Comment by Senyu** [comment] 2023-10-05 05:24
@Alex313031 Great! I just tested and Supermium 118 and does not have the problem. As for not idea what that would be, it says in the release of Supermium 118...
 - Secure DNS fixed on Windows Vista/7
It appears that was the cause of the problem.
So this problem is fixed as soon as the next version of thorium-win7 is released.

**Comment by Alex313031** [comment] 2023-10-06 11:44
@Senyu Well, Windows 7 ESU and Windows server 2012/2012 R2 (based on Win 8.0 and 8.1, respecitvely) support is ending for Chromium and Electron on October 10th. On that day, I will be making a final 109 release of Thorium, and make some vanilla builds of Chromium for whoever wants them. I would like you to compare Thorium and Chromium on that day, to see if it was something in Thorium causing the issue.

After that day, I will make builds based on Supermium 118.

**Comment by Senyu** [comment] 2023-10-11 05:14
@Alex313031 Okay, I'll do it as soon as the final version 109 of Thorium release, just waiting now.

**Comment by Senyu** [comment] 2023-10-21 09:36
@Alex313031 the problem of patreon.
Doesn't happen on version 109.0.5414.169 for me, only on the previous version of Thorium.
So this issue is resolved and can be closed.

But something else happened.

**Screenshots**
![errscss](https://github.com/Alex313031/thorium-win7/assets/75548744/ceb7d773-69ac-4ba5-b090-e2354d5637d9)

When I opening a fandom page this happens, but when reload the page again, the page loads without any problems and no more errors.
And no, Chromium doesn't have this problem.
If you want to know if the Supermium 118 has this problem... it doesn't.

**Screenshots**
![add](https://github.com/Alex313031/thorium-win7/assets/75548744/fea6a53d-11fd-40e0-bc65-f8233461d967)

Also it looks like you forgot of add it in the 6th Release.
Or not... 😅

**Comment by gz83** [comment] 2023-10-22 11:43
In the next major version update, this problem should be solved or alleviated.

**Comment by Alex313031** [comment] 2024-01-11 01:27
@Senyu Thorium M119 beta is out, this the final release coming tommorow.

**Closed by Alex313031** 2024-01-11 01:27 UTC
